apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  route:
    receiver: "email"
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashLooping
      repeatInterval: 10m
  receivers:
  - name: "email"
    emailConfigs:
    - to: "<to-email>"
      from: "<your-email>"
      smarthost: "smtp.gmail.com:587"
      authIdentity: "<your-email>"
      authUsername: "<your-email>"
      authPassword: 
        name: gmail-auth
        key: password